/*
 * LAL-free IMRPhenomTPHM interface, based on LALSimulation IMRPhenomTPHM.
 * Copyright (C) 2020 Hector Estelles
 * Port and subsequent modifications: Copyright (C) 2026 Neil Cornish
 * SPDX-License-Identifier: GPL-2.0-or-later
 * See the GNU GPL for copying terms and warranty disclaimer.
 */

#ifndef IMRPHENOMTPHM_H
#define IMRPHENOMTPHM_H

#include <complex.h>

#include "IMRPhenomTHM.h"
#include "IMRPhenomTPHM_Precession.h"
#include "IMRPhenomTPHM_Rotation.h"

#ifdef __cplusplus
extern "C" {
#endif

#define IMRPHENOMTPHM_MAX_CARRIERS 5
#define IMRPHENOMTPHM_INERTIAL_MODE_COUNT 32

/*
 * Merger/ringdown reconstruction policy.
 *
 * CONSISTENT uses the evolved precessing remnant spin throughout the carrier
 * merger and ringdown.  LAL_COMPATIBLE reproduces LAL's current default
 * PhenomTPHMMergerVersion=1 behavior: the aligned-spin remnant continues to
 * drive selected orbital quantities while the evolved spin enters selected
 * precessing phase and amplitude coefficients.  It also preserves LAL's
 * cadence-dependent numerical-angle indexing conventions.  The latter is
 * provided for controlled cross-checks, not as the physical default of this
 * implementation.
 */
typedef enum
{
    IMRPHENOMTPHM_RECONSTRUCTION_CONSISTENT = 0,
    IMRPHENOMTPHM_RECONSTRUCTION_LAL_COMPATIBLE = 1
} IMRPhenomTPHMMergerReconstruction;

/*
 * LAL-free IMRPhenomTPHM state.
 *
 * The numerical precession equations are driven by the original aligned-spin
 * PhenomT 22 frequency.  After that evolution supplies the precessing remnant
 * spin, the default carrier is reconstructed consistently with that spin for
 * the merger and ringdown.  The optional LAL-compatible reconstruction keeps
 * LAL's mixed aligned/precessing remnant treatment for diagnostic comparisons.
 * Keeping the driver and carrier objects separate avoids feeding the
 * reconstructed ringdown back into the PN precession evolution.
 */
typedef struct
{
    IMRPhenomTHM precession_driver;
    IMRPhenomTHM carrier;
    IMRPhenomTPHMPrecessionConfig precession;
    IMRPhenomTPHMPrecessionSummary precession_summary;
    IMRPhenomTHMMode carrier_modes[IMRPHENOMTPHM_MAX_CARRIERS];
    int ncarriers;
    int active_ell[IMRPHENOMTPHM_MAX_ELL + 1];
    IMRPhenomTPHMRotation j_to_l0[IMRPHENOMTPHM_MAX_ELL + 1];
    IMRPhenomTPHMMergerReconstruction merger_reconstruction;
    int initialized;
} IMRPhenomTPHM;

/*
 * Initialize the numerical-precession (version-300 style) TPHM model.
 *
 * modes names co-precessing positive-|m| carriers.  Negative m entries are
 * accepted as aliases for their positive partners and duplicate +/- entries
 * are folded.  Passing NULL or nmodes<=0 selects 21, 22, 33, 44, and 55.
 * Spin vectors are dimensionless and are specified in the L0 frame at
 * precession->tau_ref, where Lhat=(0,0,1).
 */
int IMRPhenomTPHMInitialize(IMRPhenomTPHM *model,
                            double m1,
                            double m2,
                            const IMRPhenomTPHMPrecessionConfig *precession,
                            const IMRPhenomTHMMode *modes,
                            int nmodes);

/*
 * Explicit reconstruction-policy entry point.  The ordinary initializer
 * above selects IMRPHENOMTPHM_RECONSTRUCTION_CONSISTENT.
 */
int IMRPhenomTPHMInitializeWithReconstruction(
    IMRPhenomTPHM *model,
    double m1,
    double m2,
    const IMRPhenomTPHMPrecessionConfig *precession,
    const IMRPhenomTHMMode *modes,
    int nmodes,
    IMRPhenomTPHMMergerReconstruction reconstruction);

void IMRPhenomTPHMDestroy(IMRPhenomTPHM *model);

/*
 * Fixed sample-major index for an inertial-frame mode:
 *
 *   modes[(size_t)i*IMRPHENOMTPHM_INERTIAL_MODE_COUNT + index(ell,m)].
 *
 * The 32 slots contain all m for ell=2,...,5, including modes generated by
 * twisting even when their co-precessing carriers vanish.
 */
int IMRPhenomTPHMInertialModeIndex(int ell, int emm);

/*
 * Evaluate the complete twisted-up waveform on a strictly increasing tau=t/M
 * grid.  phi22_at_start fixes the co-precessing 22 phase at tau[0].
 *
 * j_modes and l0_modes are optional sample-major arrays of n*32 complex
 * samples.  strain is the optional complex observer strain
 * hplus-i hcross in the L0 frame.  At least one of these outputs is required.
 * Any of alpha, beta, and gamma may be NULL; supplied arrays receive the
 * co-precessing-to-J Euler angles.  Amplitudes retain the normalization of the
 * stripped IMRPhenomTHM model (no distance factor is added here).
 */
int IMRPhenomTPHMEvaluateGrid(
    IMRPhenomTPHM *model,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    double complex *j_modes,
    double complex *l0_modes,
    double complex *strain,
    double *alpha,
    double *beta,
    double *gamma);

/*
 * Evaluate the observer strain and its carrier-phase quadrature in one
 * twist-up.  For every populated co-precessing +m carrier, the quadrature
 * applies phase -> phase+pi/2 before reconstructing the -m partner and
 * rotating the pair.  If
 *
 *   strain            = hplus - i hcross,
 *   strain_quadrature = hplus_q - i hcross_q,
 *
 * then hplus-i hplus_q and hcross-i hcross_q are the complex carrier
 * signals consumed by the partitioned-FFT TDI path.  This avoids unfolding
 * the twisted waveform into its 74 inertial-frame sidebands.
 *
 * strain and strain_quadrature are both required.  The mode and Euler-angle
 * outputs retain the same meaning as IMRPhenomTPHMEvaluateGrid().
 */
int IMRPhenomTPHMEvaluateGridWithQuadrature(
    IMRPhenomTPHM *model,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    double complex *j_modes,
    double complex *l0_modes,
    double complex *strain,
    double complex *strain_quadrature,
    double *alpha,
    double *beta,
    double *gamma);

/*
 * Resolve the twisted waveform by co-precessing folded carrier.  Output uses
 * carrier-major storage, carrier_strain[k*n+i], in the same order as
 * model->carrier_modes.  The sum over k exactly reproduces strain and
 * strain_quadrature from IMRPhenomTPHMEvaluateGridWithQuadrature().
 *
 * carrier_omega optionally receives the dimensionless co-precessing carrier
 * angular frequency d phase/d(t/M).  It is a clean central track for planning
 * narrow heterodyned blocks; the Euler-angle sideband width is deliberately
 * kept separate and can be added by the caller.
 */
int IMRPhenomTPHMEvaluateCarrierGridWithQuadrature(
    IMRPhenomTPHM *model,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    double complex *carrier_strain,
    double complex *carrier_strain_quadrature,
    double *carrier_omega,
    double *alpha,
    double *beta,
    double *gamma);

/*
 * All-carrier evaluation using a precomputed physical precession trajectory.
 * This is the carrier-major counterpart of the selected-carrier interface
 * below and lets grouped-envelope builders share the phase construction and
 * rotation setup across every parent carrier.
 */
int IMRPhenomTPHMEvaluateCarrierGridWithQuadratureAndEuler(
    IMRPhenomTPHM *model,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    const double *alpha,
    const double *beta,
    const double *gamma,
    double complex *carrier_strain,
    double complex *carrier_strain_quadrature,
    double *carrier_omega);

/* Compact n-sample version for one entry of model->carrier_modes. */
int IMRPhenomTPHMEvaluateSelectedCarrierGridWithQuadrature(
    IMRPhenomTPHM *model,
    int carrier_index,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    double complex *carrier_strain,
    double complex *carrier_strain_quadrature,
    double *carrier_omega,
    double *alpha,
    double *beta,
    double *gamma);

/*
 * Selected-carrier evaluation using a precomputed physical precession
 * trajectory.  alpha, beta, and gamma must correspond to tau and follow the
 * same frame and minimal-rotation convention as model->precession.  This is
 * used by partitioned transforms to share one adaptive SpinTaylor evolution
 * across many overlapping FFT blocks; it does not factor the twist-up out of
 * the carrier.
 */
int IMRPhenomTPHMEvaluateSelectedCarrierGridWithQuadratureAndEuler(
    IMRPhenomTPHM *model,
    int carrier_index,
    int n,
    const double *tau,
    double phi22_at_start,
    double observer_theta,
    double observer_phi,
    double polarization,
    const double *alpha,
    const double *beta,
    const double *gamma,
    double complex *carrier_strain,
    double complex *carrier_strain_quadrature,
    double *carrier_omega);

#ifdef __cplusplus
}
#endif

#endif
